name: ChatGuard
main: ru.Den_Abr.ChatGuard.ChatGuardPlugin
version: 7.3.2
author: Den_Abr
description: Guard for your chat
softdepend: [ProtocolLib, AuthMe]
commands:
    cg:
       description: ChatGuard commands.
       usage: /<command>
       aliases: [chatguard]